[build]
build-std = true
xargo = false
zig = false
default-target = "armv5te-unknown-linux-musleabi"
#pre-build = [
#    "dpkg --add-architecture $CROSS_DEB_ARCH", 
#    "apt-get update && apt-get --assume-yes install libusb-dev:$CROSS_DEB_ARCH libftdi1:$CROSS_DEB_ARCH libftdi1-dev:$CROSS_DEB_ARCH"
#]
