[package]
name = "arrange-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrange = { path="../arrange", features = ["ftdi"] }
env_logger = "0.11.3"
log = "0.4.21"
text_io = "0.1.12"
