[package]
name = "arrange-iceprog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrange = { path="../arrange", features = ["ftdi"] }
env_logger = { workspace = true }
log = { workspace = true }
